import { BoardMember } from "../types/boardMember";

export const boardMembers: BoardMember[] = [
  {
    name: "Felipe Assef",
    picture: "/assef.jpeg",
    major: "Human Biology: Health&Disease Specialist",
    year: "3rd",
    position: "president",
    city: "São Paulo, SP",
    linkedin: "https://www.linkedin.com/in/felipe-schultz-assef-5002b31b2/",
  },
  {
    name: "Maria Eduarda Fonseca",
    picture: "/duda.jpeg",
    major: "Global Health Specialist",
    year: "3rd",
    position: "vicePresident",
    city: "Montes Claros, MG",
    linkedin: "https://www.linkedin.com/in/duda-fonseca/",
  },
  {
    name: "Luísa Gerhard",
    picture: "/gaio.jpeg",
    major: "Pharmacology and Biomed Toxicology",
    year: "3rd",
    position: "externalRelations",
    city: "São Paulo, SP",
    linkedin: "https://www.linkedin.com/in/lu%C3%ADsa-gerhard-563743260/",
  },
  {
    name: "Gaio Augusto",
    picture: "/gaio.jpeg",
    major: "Computer Engineering",
    year: "3rd",
    position: "finance",
    city: "Curitiba, PR",
    linkedin: "https://www.linkedin.com/in/gaioaugusto/",
  },
  {
    name: "Laura Ferreira",
    picture: "/laura.jpeg",
    major: "Biological Chemistry",
    year: "3rd",
    position: "eventsCoordinator",
    city: "São Paulo, SP",
    linkedin: "https://www.linkedin.com/in/laura-ferreira-6a6962286/",
  },
  {
    name: "Carolina Galhardo",
    picture: "/gaio.jpeg",
    major: "Human Biology and Immunology",
    year: "3rd",
    position: "eventsCoordinator",
    city: "Rio de Janeiro, RJ",
    linkedin:
      "https://www.linkedin.com/in/carolina-ribeiro-galhardo-1645101b6/",
  },
  {
    name: "Bruna Borer",
    picture: "/gaio.jpeg",
    major: "Psychology and Cinema Studies",
    year: "3rd",
    position: "communication",
    city: "São Paulo, SP",
  },
  {
    name: "Paulo Maia",
    picture: "/gaio.jpeg",
    major: "Mechanical Engineering",
    year: "3rd",
    position: "firstYearOfficer",
    city: "Teresina, PI",
    linkedin: "https://www.linkedin.com/in/paulo-cortellazzi/",
  },
  {
    name: "Liliana Wu",
    picture: "/liliana.jpeg",
    major: "PhD Psychology",
    position: "graduateRep",
    city: "Salvador, BA",
    linkedin: "https://www.linkedin.com/in/liliana-wu-20530212b/",
  },

  {
    name: "Yasmin Martins",
    picture: "/yasminUtsc.jpeg",
    major: "Co-op Life Sciences (Neuroscience)",
    year: "2nd",
    position: "utscRep",
    city: "Manaus, AM",
    linkedin: "https://www.linkedin.com/in/yasmin-ladislau-martins/",
  },
  {
    name: "Yasmin Mendonça",
    picture: "/liliana.jpeg",
    major: "Communications (CCIT)",
    year: "2nd",
    position: "utmRep",
    city: "Belém, PA",
    linkedin: "https://www.linkedin.com/in/yasminmendon%C3%A7a/",
  },
];
