import { BoardMember } from "../types/boardMember";

export const boardMembers: BoardMember[] = [
    {
        name: "Gaio Augusto",
        picture: "/boardImages/co_pres_1.jpeg",
        major: "Computer Engineering",
        year: "fourthYear",
        position: "coPresident",
        city: "Curitiba, PR",
        linkedin: "https://www.linkedin.com/in/gaioaugusto/",
    },
    {
        name: "Henrique Braz",
        picture: "/boardImages/co_pres_2.jpeg",
        major: "Mechanical Engineering",
        year: "thirdYear",
        position: "coPresident",
        city: "Curitiba, PR",
        linkedin: "https://www.linkedin.com/in/henriquebraz/",
    },
    {
        name: "José Aparecido",
        picture: "/boardImages/finance.jpg",
        major: "Microbiology and Health & Disease",
        year: "thirdYear",
        position: "finance",
        city: "Belo Horizonte, MG",
        linkedin: "https://www.linkedin.com/in/jos%C3%A9-aparecido/",
    },
    {
        name: "Maria Eduarda Queiroz",
        picture: "/boardImages/digitalTech.jpg",
        major: "Computer Science",
        year: "secondYear",
        position: "digitalCoordinator",
        city: "Recife, PE",
        linkedin: "https://www.linkedin.com/in/mariaeduardameloqueiroz",
    },
    {
        name: "Isabela Barcelos",
        picture: "/boardImages/externalRelations.jpeg",
        major: "Engineering Science (BME)",
        year: "fourthYear",
        position: "externalRelations",
        city: "Goiânia, GO",
        linkedin: "https://www.linkedin.com/in/isabelabarcelos/",
    },
    {
        name: "Gabrielle Correa",
        picture: "/boardImages/events1.jpeg",
        major: "International Relations, Psychology, and Political Science",
        year: "thirdYear",
        position: "eventsCoordinator",
        city: "Manaus, AM",
        linkedin: "https://www.linkedin.com/in/gabrielle-correa-de-andrade-957020338/",
    },
    {
        name: "Sabrina Dodge Terra",
        picture: "/boardImages/events2.jpeg",
        major: "Life Sciences",
        year: "thirdYear",
        position: "eventsCoordinator",
        city: "São Paulo, SP",
        linkedin: "https://www.linkedin.com/in/sabrina-dodge-terra-26818030b/",
    },
    {
        name: "Ana Martinez",
        picture: "/boardImages/outreach.jpeg",
        major: "Political Sciences",
        year: "thirdYear",
        position: "outreach",
        city: "Avare, SP",
        linkedin: "https://www.linkedin.com/in/ana-quintas-arthuzo-martinez/",
    },
    {
        name: "Clara Kaminski",
        picture: "/boardImages/socialMediaRep.jpg",
        major: "International Relations and Public Policy",
        year: "thirdYear",
        position: "socialRepresentative",
        city: "São Paulo, SP",
        linkedin: "https://www.linkedin.com/in/clara-guimar%C3%A3es-gil-kaminski-53a8b6345/",
    },
    {
        name: "Tomás Souto",
        picture: "/boardImages/firstYearRep.jpg",
        major: "Book and Media Studies",
        year: "thirdYear",
        position: "firstYearOfficer",
        city: "Rio de Janeiro, RJ",
        linkedin: "https://www.linkedin.com/in/tom%C3%A1s-souto-28a0a02b4/",
    },
    {
        name: "Ana Luiza Miranda Guimarães",
        picture: "/boardImages/gradRep.jpg",
        major: "PhD Experimental Psychology",
        year: "secondYear",
        position: "graduateRep",
        city: "Goiânia, GO",
        linkedin: "https://www.linkedin.com/in/ana-miranda0304/",
    },
    {
        name: "Camille Dornellas",
        picture: "/boardImages/utmRep.jpg",
        major: "Professional Writing & Communication and Political Science",
        year: "secondYear",
        position: "utmRep",
        city: "Belo Horizonte, MG",
        linkedin: "https://www.linkedin.com/in/camille-dornellas-a17838212/",
    },
];
